/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class faiss_FaissJni */

#ifndef _Included_faiss_FaissJni
#define _Included_faiss_FaissJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     faiss_FaissJni
 * Method:    cppCtor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_faiss_FaissJni_cppCtor
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     faiss_FaissJni
 * Method:    cppAddItem
 * Signature: (I[F)V
 */
JNIEXPORT void JNICALL Java_faiss_FaissJni_cppAddItem
  (JNIEnv *, jobject, jint, jfloatArray);

/*
 * Class:     faiss_FaissJni
 * Method:    cppGetNearestByVector
 * Signature: ([FI)[I
 */
JNIEXPORT jintArray JNICALL Java_faiss_FaissJni_cppGetNearestByVector
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     faiss_FaissJni
 * Method:    cppGetNearestByVectorK
 * Signature: ([FII)[I
 */
JNIEXPORT jintArray JNICALL Java_faiss_FaissJni_cppGetNearestByVectorK
  (JNIEnv *, jobject, jfloatArray, jint, jint);

/*
 * Class:     faiss_FaissJni
 * Method:    cppGetNearestByItem
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_faiss_FaissJni_cppGetNearestByItem
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     faiss_FaissJni
 * Method:    cppGetNearestByItemK
 * Signature: (III)[I
 */
JNIEXPORT jintArray JNICALL Java_faiss_FaissJni_cppGetNearestByItemK
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     faiss_FaissJni
 * Method:    cppBuild
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_faiss_FaissJni_cppBuild
  (JNIEnv *, jobject, jint);

/*
 * Class:     faiss_FaissJni
 * Method:    cppSave
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_faiss_FaissJni_cppSave
  (JNIEnv *, jobject, jstring);

/*
 * Class:     faiss_FaissJni
 * Method:    cppLoad
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_faiss_FaissJni_cppLoad
  (JNIEnv *, jobject, jstring);

/*
 * Class:     faiss_FaissJni
 * Method:    cppGetItemVector
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_faiss_FaissJni_cppGetItemVector
  (JNIEnv *, jobject, jint);

/*
 * Class:     faiss_FaissJni
 * Method:    cppGetDistance
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_faiss_FaissJni_cppGetDistance
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     faiss_FaissJni
 * Method:    cppSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_faiss_FaissJni_cppSize
  (JNIEnv *, jobject);

/*
 * Class:     faiss_FaissJni
 * Method:    cppSetSeed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_faiss_FaissJni_cppSetSeed
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
