/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class faiss_FaissJni */

#ifndef _Included_faiss_FaissJni
#define _Included_faiss_FaissJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     faiss_FaissJni
 * Method:    cppCtor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_faiss_FaissJni_cppCtor
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     faiss_FaissJni
 * Method:    is_trained
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_faiss_FaissJni_is_1trained
  (JNIEnv *, jobject);

/*
 * Class:     faiss_FaissJni
 * Method:    train
 * Signature: (I[F)V
 */
JNIEXPORT void JNICALL Java_faiss_FaissJni_train
  (JNIEnv *, jobject, jint, jfloatArray);

/*
 * Class:     faiss_FaissJni
 * Method:    add
 * Signature: (I[F)V
 */
JNIEXPORT void JNICALL Java_faiss_FaissJni_add
  (JNIEnv *, jobject, jint, jfloatArray);

/*
 * Class:     faiss_FaissJni
 * Method:    addWithIds
 * Signature: (I[F[J)V
 */
JNIEXPORT void JNICALL Java_faiss_FaissJni_addWithIds
  (JNIEnv *, jobject, jint, jfloatArray, jlongArray);

/*
 * Class:     faiss_FaissJni
 * Method:    search
 * Signature: (I[FI[F[I)V
 */
JNIEXPORT void JNICALL Java_faiss_FaissJni_search
  (JNIEnv *, jobject, jint, jfloatArray, jint, jfloatArray, jintArray);

/*
 * Class:     faiss_FaissJni
 * Method:    assign
 * Signature: (I[F[II)V
 */
JNIEXPORT void JNICALL Java_faiss_FaissJni_assign
  (JNIEnv *, jobject, jint, jfloatArray, jintArray, jint);

/*
 * Class:     faiss_FaissJni
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_faiss_FaissJni_reset
  (JNIEnv *, jobject);

/*
 * Class:     faiss_FaissJni
 * Method:    reconstruct
 * Signature: (I[F)V
 */
JNIEXPORT void JNICALL Java_faiss_FaissJni_reconstruct
  (JNIEnv *, jobject, jint, jfloatArray);

/*
 * Class:     faiss_FaissJni
 * Method:    reconstruct_n
 * Signature: (II[F)V
 */
JNIEXPORT void JNICALL Java_faiss_FaissJni_reconstruct_1n
  (JNIEnv *, jobject, jint, jint, jfloatArray);

/*
 * Class:     faiss_FaissJni
 * Method:    display
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_faiss_FaissJni_display
  (JNIEnv *, jobject);

/*
 * Class:     faiss_FaissJni
 * Method:    compute_residual
 * Signature: ([F[F)V
 */
JNIEXPORT void JNICALL Java_faiss_FaissJni_compute_1residual
  (JNIEnv *, jobject, jfloatArray, jfloatArray);

/*
 * Class:     faiss_FaissJni
 * Method:    get_typename
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_faiss_FaissJni_get_1typename
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
